spring:
  profiles:
    active: mock
  application:
    name: task
springdoc:
  api-docs:
    version: OPENAPI_3_0
# Example external API configuration - override in production/profile
task:
  default-account: default-account
  bank-api:
    url: ${TASK_BANK_API_URL:http://localhost:8081} # base URL for bank API (/accounts/{id}/statements/{yyyy-MM})
  outbound-api:
    url: ${TASK_OUTBOUND_API_URL:http://localhost:8082/monthly-balances} # endpoint that accepts monthly balances POST
